image: docker:19.03.12
services:
  - name: docker:19.03.12-dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]
  - name: postgres:latest
    alias: db

variables:
    CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
    DOCKER_HOST: tcp://docker:2376
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: admin
    POSTGRES_DB: db_accounting
    PG_ROOT_PASSWORD: admin

stages:
  - build
  - test

before_script:
  - echo $DOCKER_HOST
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - echo $CONTAINER_RELEASE_IMAGE
    - echo $CONTAINER_TEST_IMAGE
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE ./script.sh
