image: docker:19.03.12
services:
  - name: docker:19.03.12-dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]


variables:
    CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - test

test:
  stage: test
  script:
    - docker network create ergo
    - docker pull postgres
    - docker run --name db -network ergo -e POSTGRES_USER=admin POSTGRES_PASSWORD=admin POSTGRES_DB=db_accounting -d postgres
    - docker ps
    - docker images
    - docker logs db
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run --network ergo -d $CONTAINER_TEST_IMAGE ./script.sh
