default:
  image: docker:19.03.12
  variables:
    CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - test

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - echo $CONTAINER_RELEASE_IMAGE
    - echo $CONTAINER_TEST_IMAGE
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

services:
  - postgres:latest
variables:
  POSTGRES_USER: ergo
  POSTGRES_PASSWORD: ergo
  POSTGRES_DB: ergo
  PG_ROOT_PASSWORD: ergo

test:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE ./script.sh
