image: docker:19.03.12
services:
  - name: docker:19.03.12-dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]


variables:
    CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo $CONTAINER_RELEASE_IMAGE
    - echo $CONTAINER_TEST_IMAGE
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test:
  stage: test
  script:
    - docker network create --driver bridge ergo
    - docker pull postgres
    - echo "POSTGRES_DB=db_accounting\nPOSTGRES_USER=admin\nPOSTGRES_PASSWORD=admin\nPG_ROOT_PASSWORD=admin" >> pg-env.list
    - docker run --name db --network="ergo" --hostname="postgres" --env-file=pg-env.list -d postgres
    - docker ps
    - docker inspect db
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run --network="ergo" $CONTAINER_TEST_IMAGE ./script.sh
