image: docker:19.03.12
services:
  - name: docker:19.03.12-dind

variables:
    CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:test
    CONTAINER_DEV_IMAGE: $CI_REGISTRY:dev
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - test
  - release

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test:
  stage: test
  script:
    - docker network create --driver bridge ergo
    - docker pull postgres
    - docker run --name db -e POSTGRES_DB=db_accounting -e POSTGRES_USER=admin -e POSTGRES_PASSWORD=admin -e PG_ROOT_PASSWORD=admin --network="ergo" --hostname="db" -d postgres
    - sleep 4
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run --network="ergo" $CONTAINER_TEST_IMAGE ./script.sh

release:
  stage: release
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      variables:
        CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_DEFAULT_BRANCH
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
