# Generated by Django 2.2.3 on 2019-12-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191202_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='block_height',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
