# Generated by Django 2.2 on 2019-12-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191208_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='key',
            field=models.CharField(choices=[('TOTAL_REWARD', 'TOTAL_REWARD'), ('MAX_REWARD', 'MAX_REWARD'), ('PPLNS_N', 'PPLNS_N')], max_length=255),
        ),
        migrations.AlterField(
            model_name='share',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
