# Generated by Django 2.2.9 on 2020-01-06 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200102_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='share',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Share'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='key',
            field=models.CharField(choices=[('TOTAL_REWARD', 'TOTAL_REWARD'), ('MAX_REWARD', 'MAX_REWARD'), ('PPLNS_N', 'PPLNS_N'), ('FEE', 'FEE'), ('PERIOD_TIME', 'PERIOD_TIME'), ('REWARD_ALGORITHM', 'REWARD_ALGORITHM'), ('TRANSACTION_FEE', 'TRANSACTION_FEE'), ('MAX_NUMBER_OF_OUTPUTS', 'MAX_NUMBER_OF_OUTPUTS')], max_length=255),
        ),
    ]
