# Generated by Django 2.2.9 on 2020-01-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200106_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='periodic_withdrawal_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='key',
            field=models.CharField(choices=[('TOTAL_REWARD', 'TOTAL_REWARD'), ('MAX_REWARD', 'MAX_REWARD'), ('PPLNS_N', 'PPLNS_N'), ('FEE', 'FEE'), ('PERIOD_TIME', 'PERIOD_TIME'), ('REWARD_ALGORITHM', 'REWARD_ALGORITHM'), ('TRANSACTION_FEE', 'TRANSACTION_FEE'), ('MAX_NUMBER_OF_OUTPUTS', 'MAX_NUMBER_OF_OUTPUTS'), ('MIN_WITHDRAW_THRESHOLD', 'MIN_WITHDRAW_THRESHOLD'), ('MAX_WITHDRAW_THRESHOLD', 'MAX_WITHDRAW_THRESHOLD'), ('DEFAULT_WITHDRAW_THRESHOLD', 'DEFAULT_WITHDRAW_THRESHOLD')], max_length=255),
        ),
    ]
