# Generated by Django 2.2.9 on 2020-01-27 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200123_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_num', models.PositiveIntegerField()),
                ('invalid_num', models.PositiveIntegerField()),
                ('repetitious_num', models.PositiveIntegerField()),
                ('difficulty_sum', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='share',
            name='is_aggregated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='key',
            field=models.CharField(choices=[('TOTAL_REWARD', 'TOTAL_REWARD'), ('REWARD_FACTOR', 'REWARD_FACTOR'), ('FEE_FACTOR', 'FEE_FACTOR'), ('REWARD_FACTOR_PRECISION', 'REWARD_FACTOR_PRECISION'), ('MAX_REWARD', 'MAX_REWARD'), ('PPLNS_N', 'PPLNS_N'), ('PERIOD_TIME', 'HASH_PERIOD_TIME'), ('REWARD_ALGORITHM', 'REWARD_ALGORITHM'), ('TRANSACTION_FEE', 'TRANSACTION_FEE'), ('MAX_NUMBER_OF_OUTPUTS', 'MAX_NUMBER_OF_OUTPUTS'), ('MIN_WITHDRAW_THRESHOLD', 'MIN_WITHDRAW_THRESHOLD'), ('MAX_WITHDRAW_THRESHOLD', 'MAX_WITHDRAW_THRESHOLD'), ('DEFAULT_WITHDRAW_THRESHOLD', 'DEFAULT_WITHDRAW_THRESHOLD'), ('CONFIRMATION_LENGTH', 'confirmation length')], max_length=255),
        ),
        migrations.AddIndex(
            model_name='balance',
            index=models.Index(fields=['created_at'], name='core_balanc_created_6f8230_idx'),
        ),
        migrations.AddField(
            model_name='aggregateshare',
            name='miner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Miner'),
        ),
        migrations.AddField(
            model_name='aggregateshare',
            name='solved_share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Share'),
        ),
    ]
