# Generated by Django 2.2.9 on 2020-01-30 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200127_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('miner', 'miner address'), ('lock', 'lock address'), ('withdraw', 'withdraw address')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('address_miner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Miner')),
            ],
        ),
        migrations.AddField(
            model_name='miner',
            name='selected_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Address'),
        ),
        migrations.AddField(
            model_name='share',
            name='lock_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lock_addresses', to='core.Address'),
        ),
        migrations.AddField(
            model_name='share',
            name='miner_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miner_addresses', to='core.Address'),
        ),
        migrations.AddField(
            model_name='share',
            name='withdraw_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraw_addresses', to='core.Address'),
        ),
    ]
