# Generated by Django 2.2.9 on 2020-02-03 11:25

from django.db import migrations, models


def update_status_balance(apps, schema_editor):
    model = apps.get_model('core', 'Balance')
    model.objects.filter(status='1').update(status='immature')
    model.objects.filter(status='2').update(status='mature')
    model.objects.filter(status='3').update(status='withdraw')
    model.objects.filter(status='4').update(status='pending_withdrawal')


def reverse_status_balance(apps, schema_editor):
    model = apps.get_model('core', 'Balance')
    model.objects.filter(status='immature').update(status='1')
    model.objects.filter(status='mature').update(status='2')
    model.objects.filter(status='withdraw').update(status='3')
    model.objects.filter(status='pending_withdrawal').update(status='4')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200130_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='status',
            field=models.CharField(choices=[('immature', 'immature'), ('mature', 'mature'), ('withdraw', 'withdraw'), ('pending_withdrawal', 'pending_withdrawal')], default='immature', max_length=100),
        ),
        migrations.RunPython(update_status_balance, reverse_status_balance)]
