# Generated by Django 2.2.9 on 2020-02-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200204_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='is_orphaned',
            field=models.BooleanField(default=False),
        ),
    ]
