# Generated by Django 2.2.9 on 2020-02-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200218_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miner',
            name='selected_address',
        ),
    ]
