# Generated by Django 2.2.9 on 2020-02-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200223_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='pow_identity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='key',
            field=models.CharField(choices=[('POOL_BASE_FACTOR', 'Pool base factor'), ('TOTAL_REWARD', 'TOTAL_REWARD'), ('REWARD_FACTOR', 'REWARD_FACTOR'), ('FEE_FACTOR', 'FEE_FACTOR'), ('REWARD_FACTOR_PRECISION', 'REWARD_FACTOR_PRECISION'), ('MAX_REWARD', 'MAX_REWARD'), ('PPLNS_N', 'PPLNS_N'), ('REWARD_ALGORITHM', 'REWARD_ALGORITHM'), ('TRANSACTION_FEE', 'TRANSACTION_FEE'), ('MAX_NUMBER_OF_OUTPUTS', 'MAX_NUMBER_OF_OUTPUTS'), ('MIN_WITHDRAW_THRESHOLD', 'MIN_WITHDRAW_THRESHOLD'), ('MAX_WITHDRAW_THRESHOLD', 'MAX_WITHDRAW_THRESHOLD'), ('DEFAULT_WITHDRAW_THRESHOLD', 'DEFAULT_WITHDRAW_THRESHOLD'), ('CONFIRMATION_LENGTH', 'confirmation length'), ('THRESHOLD_HEIGHT', 'latest allowed height for mining'), ('THRESHOLD_TIMESTAMP', 'timestamp diff allowed to miner')], max_length=255),
        ),
    ]
