# Generated by Django 2.2.10 on 2020-03-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200303_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
