# Generated by Django 2.2.9 on 2020-05-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200309_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='difficulty',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
