# Generated by Django 2.2.13 on 2020-06-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200511_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.FloatField()),
                ('pool', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
