# Generated by Django 2.2.9 on 2020-07-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200622_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(blank=True, max_length=200, null=True)),
                ('tx_body', models.TextField()),
                ('inputs', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='balance',
            name='tx_id',
        ),
        migrations.AddField(
            model_name='balance',
            name='actual_payment',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='balance',
            name='tx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Transaction'),
        ),
    ]
