# Generated by Django 2.2.13 on 2020-09-16 00:04

from django.db import migrations, models


def remove_additional_category(apps, schema_editor):
    model = apps.get_model('core', 'Address')
    model.objects.filter(category__in=["lock", "withdraw"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200717_1545'),
    ]

    operations = [
        migrations.RunPython(
            remove_additional_category
        )
    ]
