# Generated by Django 2.2.13 on 2020-09-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200916_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='category',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_miner',
            new_name='miner',
        ),
        migrations.RemoveField(
            model_name='share',
            name='lock_address',
        ),
        migrations.RemoveField(
            model_name='share',
            name='withdraw_address',
        )
    ]
